# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_spyctable_wrappers", use_symbols = TRUE, package_name = "spyctable")

#' @docType package
#' @usage NULL
#' @useDynLib spyctable, .registration = TRUE
NULL

filter_from_values_vec <- function(values_vec, data) .Call(wrap__filter_from_values_vec, values_vec, data)

#' @export
build_spyctable_html <- function(data, names, nrow, format, na, id) .Call(wrap__build_spyctable_html, data, names, nrow, format, na, id)


# nolint end
